-- Create contributions table
CREATE TABLE contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    category TEXT NOT NULL,
    ngobe_text TEXT NOT NULL,
    spanish_text TEXT NOT NULL,
    region TEXT,
    audio_lento_url TEXT,
    audio_rapido_url TEXT,
    status TEXT DEFAULT 'pending'
);

-- Enable Row Level Security (RLS)
ALTER TABLE contributions ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Allow public read access" ON contributions
    FOR SELECT
    USING (true);

CREATE POLICY "Allow authenticated insert" ON contributions
    FOR INSERT
    WITH CHECK (auth.role() = 'authenticated');

-- Storage bucket for audios (Ensure you have storage extension enabled if not using the dashboard directly to create bucket)
INSERT INTO storage.buckets (id, name, public) VALUES ('audios', 'audios', true) ON CONFLICT DO NOTHING;

-- RLS policies for storage bucket
CREATE POLICY "Allow public access to audios" ON storage.objects
    FOR SELECT
    USING (bucket_id = 'audios');

CREATE POLICY "Allow authenticated insert to audios" ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'audios' AND auth.role() = 'authenticated');
