-- Create contributions table
CREATE TABLE contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('Palabra', 'Frase', 'Cuento', 'Canción')),
    ngobe_text TEXT NOT NULL,
    spanish_text TEXT NOT NULL,
    region TEXT,
    audio_lento_url TEXT,
    audio_rapido_url TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected'))
);

-- Enable Row Level Security (RLS)
ALTER TABLE contributions ENABLE ROW LEVEL SECURITY;

-- Create Policies
CREATE POLICY "Users can read approved contributions" ON contributions
    FOR SELECT
    USING (auth.role() = 'authenticated' AND status = 'approved');

CREATE POLICY "Users can read own contributions" ON contributions
    FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own contributions" ON contributions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Storage bucket for audios (Ensure you have storage extension enabled if not using the dashboard directly to create bucket)
INSERT INTO storage.buckets (id, name, public) VALUES ('audios', 'audios', false) ON CONFLICT DO NOTHING;

-- RLS policies for storage bucket
CREATE POLICY "Allow authenticated insert to audios" ON storage.objects
    FOR INSERT
    WITH CHECK (bucket_id = 'audios' AND auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated read from audios" ON storage.objects
    FOR SELECT
    USING (bucket_id = 'audios' AND auth.role() = 'authenticated');
