-- ========================================================
-- SCRIPT COMPLETO DE CONFIGURACIÓN DE BASE DE DATOS
-- Ejecuta este script en el SQL Editor de Supabase para inicializar todo.
-- ========================================================

-- 0. LIMPIEZA DE TABLAS PREVIAS (Para evitar conflictos de esquemas antiguos)
DROP TABLE IF EXISTS public.contributions CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- --------------------------------------------------------
-- 1. TABLA DE PERFILES (profiles)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    rol TEXT NOT NULL DEFAULT 'colaborador' CHECK (rol IN ('superadmin', 'maestro', 'colaborador', 'aprendiz')),
    estado TEXT NOT NULL DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobado', 'bloqueado')),
    comunidad TEXT,
    nombre_completo TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------------
-- 2. TABLA DE APORTACIONES (contributions)
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.contributions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
    category TEXT NOT NULL,
    ngobe_text TEXT NOT NULL,
    spanish_text TEXT NOT NULL,
    region TEXT,
    audio_lento_url TEXT,
    audio_rapido_url TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    transcripcion_fonetica TEXT,
    metadatos_linguisticos JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.contributions ENABLE ROW LEVEL SECURITY;

-- --------------------------------------------------------
-- 3. FUNCIONES DE SEGURIDAD Y DE CONTROL (SECURITY DEFINER)
-- --------------------------------------------------------

-- A. Verificar si el usuario es superadmin
CREATE OR REPLACE FUNCTION public.is_superadmin()
RETURNS BOOLEAN AS $$
DECLARE
    is_admin BOOLEAN;
BEGIN
    SELECT (rol = 'superadmin') INTO is_admin FROM public.profiles WHERE id = auth.uid();
    RETURN COALESCE(is_admin, FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- B. Verificar si el usuario es maestro o administrador aprobado
CREATE OR REPLACE FUNCTION public.is_maestro_or_admin()
RETURNS BOOLEAN AS $$
DECLARE
    user_role TEXT;
    user_status TEXT;
BEGIN
    SELECT rol, estado INTO user_role, user_status FROM public.profiles WHERE id = auth.uid();
    RETURN COALESCE(user_role IN ('maestro', 'superadmin') AND user_status = 'aprobado', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- C. Trigger para proteger los campos 'rol' y 'estado' de modificaciones por usuarios no superadmin
CREATE OR REPLACE FUNCTION public.protect_profile_fields()
RETURNS TRIGGER AS $$
BEGIN
    IF NOT public.is_superadmin() THEN
        IF NEW.rol IS DISTINCT FROM OLD.rol THEN
            NEW.rol = OLD.rol;
        END IF;
        IF NEW.estado IS DISTINCT FROM OLD.estado THEN
            NEW.estado = OLD.estado;
        END IF;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- D. Trigger para crear perfil automáticamente al registrarse
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, rol, estado, nombre_completo, comunidad)
    VALUES (NEW.id, 'colaborador', 'pendiente', NULL, NULL);
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- --------------------------------------------------------
-- 4. MITIGACIÓN DE ADVERTENCIAS DE LINTER DE SUPABASE (HARDENING)
-- --------------------------------------------------------
-- Por defecto, PostgreSQL permite que PUBLIC (cualquier rol anónimo o autenticado) ejecute las funciones SECURITY DEFINER.
-- Para solucionar las advertencias del linter y evitar ejecuciones indebidas via REST API / RPC, revocamos el permiso de ejecución.

REVOKE EXECUTE ON FUNCTION public.is_superadmin() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.is_maestro_or_admin() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_profile_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;

-- Revocar privilegios en rls_auto_enable de forma segura si la función existe
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_proc JOIN pg_namespace ON pg_proc.pronamespace = pg_namespace.oid WHERE proname = 'rls_auto_enable' AND nspname = 'public') THEN
        EXECUTE 'REVOKE EXECUTE ON FUNCTION public.rls_auto_enable() FROM PUBLIC, anon, authenticated;';
    END IF;
END $$;

-- --------------------------------------------------------
-- 5. ASOCIACIÓN DE TRIGGERS
-- --------------------------------------------------------
DROP TRIGGER IF EXISTS ensure_protected_profile_fields ON public.profiles;
CREATE TRIGGER ensure_protected_profile_fields
    BEFORE UPDATE ON public.profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.protect_profile_fields();

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_new_user();

-- --------------------------------------------------------
-- 6. POLÍTICAS RLS (Row Level Security)
-- --------------------------------------------------------

-- A. Políticas para la tabla 'profiles'
DROP POLICY IF EXISTS "Usuarios pueden leer su propio perfil y superadmins todos" ON public.profiles;
CREATE POLICY "Usuarios pueden leer su propio perfil y superadmins todos" ON public.profiles
    FOR SELECT USING (auth.uid() = id OR public.is_superadmin());

DROP POLICY IF EXISTS "Usuarios pueden actualizar su perfil y superadmins todos" ON public.profiles;
CREATE POLICY "Usuarios pueden actualizar su perfil y superadmins todos" ON public.profiles
    FOR UPDATE USING (auth.uid() = id OR public.is_superadmin());

-- B. Políticas para la tabla 'contributions'
DROP POLICY IF EXISTS "Users can read approved contributions" ON public.contributions;
CREATE POLICY "Users can read approved contributions" ON public.contributions
    FOR SELECT USING (status = 'approved');

DROP POLICY IF EXISTS "Users can read own contributions" ON public.contributions;
CREATE POLICY "Users can read own contributions" ON public.contributions
    FOR SELECT USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can insert own contributions" ON public.contributions;
CREATE POLICY "Users can insert own contributions" ON public.contributions
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Maestros and admins can update contributions" ON public.contributions;
CREATE POLICY "Maestros and admins can update contributions" ON public.contributions
    FOR UPDATE USING (public.is_maestro_or_admin()) WITH CHECK (public.is_maestro_or_admin());

DROP POLICY IF EXISTS "Maestros and admins can read all contributions" ON public.contributions;
CREATE POLICY "Maestros and admins can read all contributions" ON public.contributions
    FOR SELECT USING (public.is_maestro_or_admin());

-- --------------------------------------------------------
-- 7. CONFIGURACIÓN DEL BUCKET DE AUDIOS
-- --------------------------------------------------------
-- Asegurar que el bucket 'audios' existe y es privado
INSERT INTO storage.buckets (id, name, public)
VALUES ('audios', 'audios', false)
ON CONFLICT (id) DO NOTHING;

-- Asegurar que el bucket sea privado (resuelve el warning public_bucket_allows_listing)
UPDATE storage.buckets SET public = false WHERE id = 'audios';

-- Políticas de almacenamiento
DROP POLICY IF EXISTS "Allow authenticated read from audios" ON storage.objects;
CREATE POLICY "Allow authenticated read from audios" ON storage.objects
    FOR SELECT TO authenticated USING (bucket_id = 'audios');

DROP POLICY IF EXISTS "Allow authenticated insert to audios" ON storage.objects;
CREATE POLICY "Allow authenticated insert to audios" ON storage.objects
    FOR INSERT TO authenticated WITH CHECK (bucket_id = 'audios');

DROP POLICY IF EXISTS "Allow owner to delete from audios" ON storage.objects;
CREATE POLICY "Allow owner to delete from audios" ON storage.objects
    FOR DELETE TO authenticated USING (bucket_id = 'audios' AND owner = auth.uid());

-- --------------------------------------------------------
-- 8. INSERCIÓN DE DATOS DE PRUEBA (MOCK DATA)
-- --------------------------------------------------------
-- Primero, insertamos los usuarios en auth.users para satisfacer la clave foránea.
-- Esto también probará que nuestro trigger de auto-perfil (handle_new_user) funcione.
INSERT INTO auth.users (id, email, aud, role)
VALUES 
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'juan@ejemplo.com', 'authenticated', 'authenticated'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'maria@ejemplo.com', 'authenticated', 'authenticated'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'lucas@ejemplo.com', 'authenticated', 'authenticated')
ON CONFLICT (id) DO NOTHING;

-- Modificamos los perfiles creados por el trigger con los roles y comunidades de prueba
INSERT INTO public.profiles (id, rol, estado, nombre_completo, comunidad)
VALUES 
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', 'colaborador', 'aprobado', 'Juan Atencio', 'Soloy (Nedrini)'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22', 'maestro', 'aprobado', 'Maestra María Bejerano', 'Kankintú (Ñö Kribo)'),
  ('a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33', 'colaborador', 'pendiente', 'Lucas Rodríguez', 'Kusapín (Ñö Kribo)')
ON CONFLICT (id) DO UPDATE 
SET 
  rol = EXCLUDED.rol,
  estado = EXCLUDED.estado,
  nombre_completo = EXCLUDED.nombre_completo,
  comunidad = EXCLUDED.comunidad;

INSERT INTO public.contributions (id, user_id, category, ngobe_text, spanish_text, region, status, transcripcion_fonetica, metadatos_linguisticos, created_at)
VALUES
  (
    1001,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'sustantivo',
    'Kri',
    'Árbol / Madera',
    'General',
    'approved',
    '/kɾi/',
    '{"formato": "m4a", "validador_id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22", "detalles_acusticos": {"calidad_estimada": "buena", "ruido_fondo": "no"}}'::jsonb,
    NOW() - INTERVAL '5 days'
  ),
  (
    1002,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'sustantivo',
    'Ñö',
    'Agua / Río',
    'Ñö Kribo',
    'approved',
    '/ɲø/',
    '{"formato": "m4a", "validador_id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22", "detalles_acusticos": {"calidad_estimada": "buena", "ruido_fondo": "no"}}'::jsonb,
    NOW() - INTERVAL '4 days'
  ),
  (
    1003,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'frase',
    'Köböre kwen',
    'Buenos días',
    'Nedrini',
    'approved',
    '/kɔ.βɔ.ɾɛ kwɛn/',
    '{"formato": "m4a", "validador_id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a22", "detalles_acusticos": {"calidad_estimada": "excelente", "ruido_fondo": "no"}}'::jsonb,
    NOW() - INTERVAL '3 days'
  )
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.contributions (id, user_id, category, ngobe_text, spanish_text, region, status, created_at)
VALUES
  (
    2001,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    'sustantivo',
    'Ngäbe',
    'Persona de la comarca / Gente',
    'General',
    'pending',
    NOW() - INTERVAL '1 hour'
  ),
  (
    2002,
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a33',
    'verbo',
    'Niken',
    'Ir / Caminar',
    'Nedrini',
    'pending',
    NOW() - INTERVAL '30 minutes'
  )
ON CONFLICT (id) DO NOTHING;
